# This is a config for E2B sandbox template.
# You can use template ID (8bbizxrcxtpyp1vus4jc) or template name (v0-clone-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-clone-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-clone-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-clone-v2')

team_id = "1d83177f-32cb-4cd5-acbd-0f4d6de51713"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-clone-v2"
template_id = "8bbizxrcxtpyp1vus4jc"
